version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    command: bash -c "sleep 10 && php-fpm"
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel 

  phpmyadmin-testing:
    image: phpmyadmin:latest
    container_name: testing_db_phpmyadmin
    restart: always
    environment:
      PMA_HOST: testing_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"  # Використайте інший порт, щоб не конфліктувати з основним phpMyAdmin
    depends_on:
      - testing_db  # Контейнер вашої тестової бази даних    
    networks:
      - laravel   

  testing_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing_db
    volumes:
      - test-db-data:/var/lib/mysql
    networks:
      - laravel    

networks:
  laravel:

volumes:
  dbdata:
  test-db-data:
